[[introduction]]

== INTRODUCTION

=== Artificial Intelligence and Machine Learning

==== Overview

Artificial Intelligence (AI) brings to mind science fiction stories about robots
and talking machines. Some might even relate Machine Learning (ML) to advanced
robots bent on destroying the world. Today this technology is more about
building intelligent systems with decision making abilities.

Think about ML as a sub-field of AI that can analyze large amounts of data and
automate analytical models. This branch of AI was born from pattern recognition
and the theory that computer can learn, and having the ability to independently
draw knowledge from experience.

==== Historically

Deep Blue computer, that could play chess in a high level championship but
that's all it could do. Presently, large data centers and huge storage capacities
make things that were believed for years to be distant concepts possible.

Writing a program to play tic-tac-toe would require a huge number of specific
conditional branches to handle even these simple moves and rules. The problem
grows significantly with more complicated games such as chess that has an
average of 35 possible moves each turn. The choices become ever more complex
as the game progresses and rules written in a structured programming language
begin to break down.

The program and its decisions for every possibility become impracticable to
manage. The rules do not need to be written by a human. With the right
instructions, the computer can learn to create its own decision trees.

==== Presently

In its basic form, ML combined with hardware-accelerated embedded systems can
reach significant improvements in image and video recognition. The reason is
a certain level of performance embedded systems have reached over the last
few years.

This explains how hardware-accelerated embedded systems have been gaining in
several types of industrial processes. Autonomous vehicles and voice control
assistants — once subjects of science fiction — have attained significant
research and development success and even consumer products in today's
marketplace.

This field boils down on spending time to write many lines of code that
eventually solve a problem by applying some type of intelligent algorithm. For
instance, some smart houses have lighting systems which automatically turn on
and off based on whether anyone is present in the room. This idea does not
amuse, but thinking about this, consider that this system is actually making
independent decisions.

==== Algorithm

The much-needed algorithms required for real-time image and video recognition
are being developed and will get it all quickly. Not just that, several
types of algorithms for different issues are being created every day and
embedded systems are fully prepared to completely embrace this technology
replacing the work of an human being.

==== Robin Bird

Machine Learning is the study of algorithms that learn from examples and
experiences instead of relying on hard-coded rules. Robin Bird solves real
world problems using only math and object-oriented programming, including
an easily extensible implementation of object-oriented classes for enthusiast
developers.

For instance, think about the following situation where it is required to write
code to recognize two types of fruit or cars or animals. This is difficult
without Machine Learning. Robin Bird can make predictions based on a huge
amount of data just by recognizing aspects and relations of patterns.

===== Classification

Problems like image, speech and character recognition belongs to a
category that is called Classification problems, which a certain given input, the
machine should be able to select a category where it belongs and labeled.

==== Robin Bird Release

This Robin Bird release includes algorithms for recognition problems. It can be
integrated with machine learning solutions from low to medium scale.

* Robin Bird Beta Release v1.0.0

<<<
