[[installation]]

=== GETTING STARTED

This library and documentation are totally experimental, providing no warranty
of a full functionatlly during these beta releases. The next steps were
tested under the `GNU/Linux Ubuntu` distribution 18.04.

==== Prerequisites Packages

Robin Bird requires a few dependencies as well as a graphical interfaces library
and library for image manipulation. This list of dependencies may increase over time:

* https://www.gtkmm.org/en/[gtkmm - C++ Interfaces for GTK+ and GNOME]
* http://www.libpng.org/pub/png/libpng.html[libpng - C functions for handling PNG images]

===== Installing Packages

These steps are required for using `Robin Bird` in a local machine for a quickly
developing and debugging work of the library. On `x86` platform, install the
following requirements:

[source,bash]
----
$ apt-get install g++ libgtkmm-3.0-dev libpng++-dev
----

===== Robin Bird Source Code

Get `Robin Bird` source code `beta` release:

[source,bash]
----
$ git clone https://github.com/diegohdorta/robin-bird.git
$ cd robin-bird/
----

Checkout the `robin-bird-beta_v1.0.0` release as follows:

[source,bash]
----
$ git checkout robin-bird-beta_v1.0.0
----

===== Robin Bird Cmake

Robin Bird uses https://cmake.org/[cmake] for a easy compilation and maintenance.
Create a build project directory, where the binaries are placed after compiling:

[source,bash]
----
$ mkdir build
$ cd build
----

===== Compilation Flags

Use the following flags for including fuzzing, samples and the lib to the
`Unix Makefile` generated by cmake:

* ROBIN_BIRD, enables `Robin Bird` library;
* SAMPLES, enables `Robin Bird` samples;
* ROBIN_BIN_INSTALL_DIR, defines where the samples are installed;
* INSTURMENT_FOR_FUZZING, enables fuzzing tests.

For a normal `Robin Bird` installation:

[source,bash]
----
$ cmake .. -DROBIN_BIRD=ON \
           -DSAMPLES=ON \
           -DINSTURMENT_FOR_FUZZING=ON \
           -DROBIN_BIN_INSTALL_DIR=/bin
$ make
----

Install the binaries and dynamic link the `Robin Bird`:

[NOTE]
====
 It may be necessary to use root privileges.
====

[source,bash]
----
$ make install
$ ldconfig
----

==== Embedded System Compilation

(to be continued)

<<<
